export function loadPartList() {
    return [
        {
            id: '5e60267fd699c2186059e7d5',
            rev: true,
            nill: false,
            variant: 'C',
            partnumber: '85245723-28',
            airlinepn: 464,
            indent: 2,
            nomenclature: 'Joyner',
            addText: 'Reese',
            misc: 'Cillum qui fugiat Lorem eu pariatur.',
            eff: 'C',
            qty: 13,
        },
        {
            id: '5e60267f71fcf8dc4453411b',
            rev: false,
            nill: false,
            variant: 'E',
            partnumber: '96646139-39',
            airlinepn: 549,
            indent: 1,
            nomenclature: 'Morgan',
            addText: 'Wiley',
            misc:
                'Consequat nulla Lorem quis ad ex commodo deserunt ut velit consectetur nostrud est officia.',
            eff: 'E',
            qty: 62,
        },
        {
            id: '5e60267f1102e15920ce2dc1',
            rev: true,
            nill: false,
            variant: 'A',
            partnumber: '87547922-42',
            airlinepn: 487,
            indent: 3,
            nomenclature: 'Lauren',
            addText: 'Oneil',
            misc: 'Enim cupidatat in in pariatur.',
            eff: 'D',
            qty: 54,
        },
        {
            id: '5e60267f126f56cdb62dd410',
            rev: false,
            nill: false,
            variant: 'C',
            partnumber: '98658332-13',
            airlinepn: 301,
            indent: 2,
            nomenclature: 'Davis',
            addText: 'Hopkins',
            misc:
                'Ipsum Lorem aute sit proident duis non ad consectetur incididunt veniam id excepteur pariatur aliquip.',
            eff: 'B',
            qty: 84,
        },
        {
            id: '5e60267f1c26f0d03e00263b',
            rev: true,
            nill: true,
            variant: 'E',
            partnumber: '99555837-93',
            airlinepn: 744,
            indent: 5,
            nomenclature: 'Nichols',
            addText: 'Mosley',
            misc:
                'Consectetur occaecat aute magna irure et minim ut pariatur esse laborum.',
            eff: 'D',
            qty: 27,
        },
        {
            id: '5e60267fc8128bd2978d9777',
            rev: true,
            nill: true,
            variant: 'D',
            partnumber: '92945529-63',
            airlinepn: 318,
            indent: 2,
            nomenclature: 'Morrow',
            addText: 'Nash',
            misc:
                'Elit fugiat anim nulla elit Lorem nulla fugiat quis culpa ex.',
            eff: 'A',
            qty: 1,
        },
        {
            id: '5e60267fb75031bc40ffb019',
            rev: true,
            nill: false,
            variant: 'C',
            partnumber: '87649923-26',
            airlinepn: 596,
            indent: 2,
            nomenclature: 'Ray',
            addText: 'Meyer',
            misc:
                'Labore nostrud do nisi incididunt magna ullamco id deserunt fugiat.',
            eff: 'A',
            qty: 75,
        },
        {
            id: '5e60267fd0fb4e1efa55a434',
            rev: true,
            nill: false,
            variant: 'D',
            partnumber: '84760034-34',
            airlinepn: 875,
            indent: 4,
            nomenclature: 'Bethany',
            addText: 'Sullivan',
            misc:
                'Enim pariatur qui incididunt est proident dolor irure voluptate in sint mollit tempor laborum.',
            eff: 'D',
            qty: 69,
        },
        {
            id: '5e60267f87ea301eeb4c0444',
            rev: false,
            nill: false,
            variant: 'C',
            partnumber: '90355520-20',
            airlinepn: 537,
            indent: 1,
            nomenclature: 'Goff',
            addText: 'Mason',
            misc: 'Fugiat excepteur do fugiat do proident velit velit est.',
            eff: 'E',
            qty: 23,
        },
        {
            id: '5e60267fee50e975330aeaa6',
            rev: true,
            nill: true,
            variant: 'C',
            partnumber: '85756431-53',
            airlinepn: 57,
            indent: 2,
            nomenclature: 'Burton',
            addText: 'Mcdaniel',
            misc:
                'Velit ullamco mollit enim eu magna incididunt laboris occaecat consequat cillum Lorem eiusmod.',
            eff: 'E',
            qty: 16,
        },
        {
            id: '5e60267f5c89798146f5ad80',
            rev: true,
            nill: false,
            variant: 'A',
            partnumber: '87349139-79',
            airlinepn: 268,
            indent: 1,
            nomenclature: 'Wooten',
            addText: 'Stuart',
            misc:
                'Laborum dolor est dolore qui incididunt consectetur nostrud nisi officia.',
            eff: 'A',
            qty: 40,
        },
        {
            id: '5e60267ffc6c6f8d90be795c',
            rev: true,
            nill: false,
            variant: 'C',
            partnumber: '91845822-56',
            airlinepn: 223,
            indent: 3,
            nomenclature: 'Alejandra',
            addText: 'Rollins',
            misc:
                'Est nisi consequat consequat anim ea excepteur exercitation sunt magna non pariatur minim est.',
            eff: 'D',
            qty: 8,
        },
        {
            id: '5e60267fd9add72a40b0caa1',
            rev: true,
            nill: false,
            variant: 'B',
            partnumber: '82346126-53',
            airlinepn: 910,
            indent: 5,
            nomenclature: 'Lopez',
            addText: 'Becker',
            misc:
                'Non reprehenderit enim irure anim laboris non dolor anim duis ex culpa reprehenderit.',
            eff: 'E',
            qty: 80,
        },
        {
            id: '5e60267f0cce16685311b30b',
            rev: false,
            nill: false,
            variant: 'A',
            partnumber: '86852130-18',
            airlinepn: 548,
            indent: 3,
            nomenclature: 'Yvonne',
            addText: 'Campbell',
            misc: 'Aute qui irure reprehenderit occaecat id do aute laborum.',
            eff: 'D',
            qty: 71,
        },
        {
            id: '5e60267fc953e911d14658a4',
            rev: false,
            nill: false,
            variant: 'B',
            partnumber: '83047033-22',
            airlinepn: 881,
            indent: 3,
            nomenclature: 'Garcia',
            addText: 'Caldwell',
            misc:
                'Ex sint aliqua laboris excepteur ut esse cupidatat anim voluptate aliquip.',
            eff: 'E',
            qty: 75,
        },
        {
            id: '5e60267fcb78735a1374e153',
            rev: true,
            nill: false,
            variant: 'E',
            partnumber: '93040727-49',
            airlinepn: 492,
            indent: 3,
            nomenclature: 'Hendricks',
            addText: 'Arnold',
            misc:
                'Eu in pariatur consequat consectetur laborum labore proident cupidatat.',
            eff: 'C',
            qty: 6,
        },
        {
            id: '5e60267f68650a04c55cc486',
            rev: false,
            nill: false,
            variant: 'A',
            partnumber: '87348431-25',
            airlinepn: 904,
            indent: 3,
            nomenclature: 'Francis',
            addText: 'Santos',
            misc: 'Sint labore occaecat ipsum excepteur.',
            eff: 'C',
            qty: 40,
        },
        {
            id: '5e60267fa2a7163c482a95c2',
            rev: true,
            nill: true,
            variant: 'B',
            partnumber: '86059231-58',
            airlinepn: 458,
            indent: 3,
            nomenclature: 'Eugenia',
            addText: 'Hood',
            misc:
                'Ad eiusmod aliqua sint magna ad anim duis ea dolor dolor labore proident.',
            eff: 'B',
            qty: 31,
        },
        {
            id: '5e60267f017b8246fba62d37',
            rev: true,
            nill: true,
            variant: 'E',
            partnumber: '97948527-23',
            airlinepn: 786,
            indent: 2,
            nomenclature: 'Dorsey',
            addText: 'Henson',
            misc: 'Et qui laborum consequat tempor sunt id irure in.',
            eff: 'D',
            qty: 91,
        },
        {
            id: '5e60267fe2585ad7a365bc8c',
            rev: false,
            nill: true,
            variant: 'E',
            partnumber: '98159538-68',
            airlinepn: 351,
            indent: 5,
            nomenclature: 'Mitzi',
            addText: 'Miranda',
            misc: 'Occaecat in cillum cupidatat ex.',
            eff: 'D',
            qty: 15,
        },
        {
            id: '5e60267f6fab2db8a71315c7',
            rev: true,
            nill: false,
            variant: 'E',
            partnumber: '92849438-53',
            airlinepn: 44,
            indent: 1,
            nomenclature: 'Hampton',
            addText: 'Sharp',
            misc:
                'Cupidatat velit consequat magna incididunt culpa ipsum enim.',
            eff: 'C',
            qty: 81,
        },
        {
            id: '5e60267f51ffa6ba5a24d1de',
            rev: false,
            nill: true,
            variant: 'C',
            partnumber: '87456334-92',
            airlinepn: 330,
            indent: 4,
            nomenclature: 'Keri',
            addText: 'Wilkinson',
            misc: 'Culpa nisi est commodo tempor fugiat labore proident sunt.',
            eff: 'A',
            qty: 75,
        },
        {
            id: '5e60267fe6f2803673fb90ba',
            rev: false,
            nill: false,
            variant: 'D',
            partnumber: '96746931-56',
            airlinepn: 269,
            indent: 2,
            nomenclature: 'Smith',
            addText: 'Chang',
            misc:
                'Nulla enim consequat quis ex exercitation aliqua sunt enim id laboris eu nostrud ut.',
            eff: 'E',
            qty: 64,
        },
        {
            id: '5e60267f9354ec172504f248',
            rev: true,
            nill: false,
            variant: 'C',
            partnumber: '98559031-30',
            airlinepn: 928,
            indent: 4,
            nomenclature: 'Peterson',
            addText: 'Walters',
            misc:
                'Pariatur proident labore deserunt excepteur voluptate minim non incididunt laboris aliqua nisi anim ad in.',
            eff: 'B',
            qty: 15,
        },
        {
            id: '5e60267f9939701198d03c5c',
            rev: true,
            nill: false,
            variant: 'B',
            partnumber: '92942627-36',
            airlinepn: 688,
            indent: 4,
            nomenclature: 'Kirk',
            addText: 'Turner',
            misc:
                'Sit voluptate dolor adipisicing aute ex tempor nulla reprehenderit.',
            eff: 'C',
            qty: 80,
        },
        {
            id: '5e60267f0cf83dd86b5e19c5',
            rev: false,
            nill: true,
            variant: 'D',
            partnumber: '81246531-84',
            airlinepn: 471,
            indent: 3,
            nomenclature: 'Kirby',
            addText: 'Wells',
            misc:
                'Amet amet consectetur in esse irure non ipsum laborum ea ea elit minim pariatur.',
            eff: 'E',
            qty: 68,
        },
        {
            id: '5e60267fd47acc42caa65022',
            rev: true,
            nill: false,
            variant: 'C',
            partnumber: '93246939-23',
            airlinepn: 696,
            indent: 1,
            nomenclature: 'Frederick',
            addText: 'Pearson',
            misc:
                'Quis velit sint culpa sunt consectetur incididunt sint reprehenderit irure consequat fugiat consequat nostrud deserunt.',
            eff: 'C',
            qty: 15,
        },
        {
            id: '5e60267f450c90421df6583d',
            rev: true,
            nill: false,
            variant: 'D',
            partnumber: '88142036-27',
            airlinepn: 627,
            indent: 5,
            nomenclature: 'Cheri',
            addText: 'Zimmerman',
            misc: 'Esse deserunt tempor amet eu excepteur.',
            eff: 'D',
            qty: 82,
        },
        {
            id: '5e60267f80e2fa0d9844a0bb',
            rev: false,
            nill: true,
            variant: 'C',
            partnumber: '93052822-00',
            airlinepn: 68,
            indent: 2,
            nomenclature: 'Mclean',
            addText: 'Roman',
            misc:
                'Non reprehenderit irure consectetur excepteur commodo in non magna velit ipsum officia incididunt.',
            eff: 'E',
            qty: 5,
        },
        {
            id: '5e60267ff052464dc3d805e3',
            rev: true,
            nill: false,
            variant: 'B',
            partnumber: '95559521-94',
            airlinepn: 740,
            indent: 1,
            nomenclature: 'Margery',
            addText: 'Conner',
            misc: 'Velit velit adipisicing elit aute magna tempor.',
            eff: 'C',
            qty: 51,
        },
        {
            id: '5e60267f29406fe0bef9bf7a',
            rev: true,
            nill: true,
            variant: 'B',
            partnumber: '86041533-75',
            airlinepn: 907,
            indent: 4,
            nomenclature: 'Burt',
            addText: 'Mack',
            misc:
                'Excepteur est exercitation Lorem id nulla proident esse cillum laborum proident.',
            eff: 'C',
            qty: 83,
        },
        {
            id: '5e60267ff90510bee2539ba5',
            rev: true,
            nill: true,
            variant: 'E',
            partnumber: '90642832-42',
            airlinepn: 875,
            indent: 1,
            nomenclature: 'Courtney',
            addText: 'Lucas',
            misc: 'Pariatur laboris duis cupidatat id laboris.',
            eff: 'D',
            qty: 25,
        },
        {
            id: '5e60267f186dc69c5248c9ab',
            rev: true,
            nill: false,
            variant: 'B',
            partnumber: '81354138-60',
            airlinepn: 962,
            indent: 3,
            nomenclature: 'Caroline',
            addText: 'Berg',
            misc:
                'Fugiat laborum qui dolore cupidatat quis id cillum veniam magna do non deserunt excepteur.',
            eff: 'C',
            qty: 92,
        },
        {
            id: '5e60267f3643b02d8ccdac1e',
            rev: true,
            nill: true,
            variant: 'A',
            partnumber: '81343435-25',
            airlinepn: 832,
            indent: 2,
            nomenclature: 'Paul',
            addText: 'Walls',
            misc: 'Quis laboris officia commodo aliquip id.',
            eff: 'D',
            qty: 5,
        },
        {
            id: '5e60267f0cc621a2dff947bd',
            rev: false,
            nill: true,
            variant: 'B',
            partnumber: '90259525-51',
            airlinepn: 31,
            indent: 2,
            nomenclature: 'Riggs',
            addText: 'Perez',
            misc:
                'Pariatur adipisicing eu non nisi reprehenderit pariatur incididunt commodo occaecat laboris.',
            eff: 'B',
            qty: 76,
        },
        {
            id: '5e60267f8f6b6db6d9050625',
            rev: true,
            nill: false,
            variant: 'B',
            partnumber: '84859939-14',
            airlinepn: 637,
            indent: 2,
            nomenclature: 'Rivera',
            addText: 'Hoffman',
            misc:
                'Quis aliqua deserunt labore sint sunt culpa cillum incididunt enim aliqua aliqua.',
            eff: 'D',
            qty: 82,
        },
        {
            id: '5e60267f34b4654cefd42b64',
            rev: true,
            nill: true,
            variant: 'D',
            partnumber: '87548222-40',
            airlinepn: 259,
            indent: 4,
            nomenclature: 'Owens',
            addText: 'Jacobs',
            misc: 'Ullamco nisi elit in nulla laborum laborum.',
            eff: 'C',
            qty: 94,
        },
        {
            id: '5e60267f982ddab8f823f606',
            rev: false,
            nill: true,
            variant: 'B',
            partnumber: '87642335-12',
            airlinepn: 253,
            indent: 3,
            nomenclature: 'Bowen',
            addText: 'Lowery',
            misc:
                'Consequat mollit dolor deserunt mollit qui aliquip sint tempor aliquip do irure aliqua do.',
            eff: 'C',
            qty: 84,
        },
        {
            id: '5e60267f1c73799dd8a3c148',
            rev: false,
            nill: false,
            variant: 'A',
            partnumber: '95542124-07',
            airlinepn: 23,
            indent: 5,
            nomenclature: 'Fisher',
            addText: 'Jefferson',
            misc:
                'Do ex aliqua velit duis ipsum incididunt incididunt sit reprehenderit esse sint dolor aliquip magna.',
            eff: 'C',
            qty: 38,
        },
        {
            id: '5e60267ff21227c9f0175a2c',
            rev: true,
            nill: true,
            variant: 'E',
            partnumber: '93458739-21',
            airlinepn: 661,
            indent: 2,
            nomenclature: 'Clara',
            addText: 'Spears',
            misc:
                'Pariatur labore elit quis labore do sunt minim ipsum cupidatat mollit ad cillum aliqua do.',
            eff: 'B',
            qty: 3,
        },
        {
            id: '5e60267fb7a3516b13d2d997',
            rev: false,
            nill: true,
            variant: 'D',
            partnumber: '84242638-09',
            airlinepn: 561,
            indent: 3,
            nomenclature: 'Velez',
            addText: 'Velasquez',
            misc:
                'Ipsum consectetur dolore labore ex id deserunt adipisicing ad adipisicing magna deserunt officia anim.',
            eff: 'B',
            qty: 85,
        },
        {
            id: '5e60267fe13c07694f6616fa',
            rev: true,
            nill: false,
            variant: 'D',
            partnumber: '89756233-95',
            airlinepn: 664,
            indent: 5,
            nomenclature: 'Dejesus',
            addText: 'Contreras',
            misc:
                'Amet commodo in aliquip elit amet non amet enim duis commodo deserunt ad.',
            eff: 'D',
            qty: 5,
        },
        {
            id: '5e60267f3832a29a3230b0b9',
            rev: true,
            nill: false,
            variant: 'D',
            partnumber: '96257323-50',
            airlinepn: 168,
            indent: 1,
            nomenclature: 'Barker',
            addText: 'Mcintyre',
            misc: 'Reprehenderit labore dolore culpa sunt sunt amet.',
            eff: 'D',
            qty: 18,
        },
        {
            id: '5e60267fc295bd93b6886633',
            rev: false,
            nill: true,
            variant: 'E',
            partnumber: '81940738-58',
            airlinepn: 223,
            indent: 3,
            nomenclature: 'Garrett',
            addText: 'Barry',
            misc: 'Ipsum exercitation do incididunt non aliqua.',
            eff: 'B',
            qty: 53,
        },
        {
            id: '5e60267f79b8d71171ede801',
            rev: true,
            nill: true,
            variant: 'A',
            partnumber: '85658530-18',
            airlinepn: 387,
            indent: 2,
            nomenclature: 'Melanie',
            addText: 'Fuentes',
            misc:
                'Et aliquip aliquip dolore commodo proident et nisi laborum et.',
            eff: 'C',
            qty: 66,
        },
        {
            id: '5e60267f88caf2943b1a058a',
            rev: true,
            nill: true,
            variant: 'A',
            partnumber: '89049425-58',
            airlinepn: 644,
            indent: 1,
            nomenclature: 'Terry',
            addText: 'Woodward',
            misc:
                'Nulla ea adipisicing anim dolore sunt irure reprehenderit culpa laborum.',
            eff: 'B',
            qty: 94,
        },
        {
            id: '5e60267faf55fdceb93eb529',
            rev: false,
            nill: false,
            variant: 'B',
            partnumber: '81340932-65',
            airlinepn: 390,
            indent: 1,
            nomenclature: 'Hilary',
            addText: 'Carr',
            misc: 'Amet cupidatat sit do ex.',
            eff: 'B',
            qty: 27,
        },
        {
            id: '5e60267fccf4b5ffc1db4b28',
            rev: true,
            nill: false,
            variant: 'C',
            partnumber: '97549728-24',
            airlinepn: 843,
            indent: 5,
            nomenclature: 'Kris',
            addText: 'Salinas',
            misc:
                'Consequat veniam ipsum anim aute elit labore cillum adipisicing cillum.',
            eff: 'C',
            qty: 49,
        },
        {
            id: '5e60267fd457d48e1a164199',
            rev: true,
            nill: true,
            variant: 'E',
            partnumber: '85540136-66',
            airlinepn: 178,
            indent: 1,
            nomenclature: 'Stefanie',
            addText: 'Goff',
            misc:
                'Velit duis dolore aliqua proident eu labore incididunt nulla do irure est incididunt sint aliquip.',
            eff: 'D',
            qty: 9,
        },
        {
            id: '5e60267f4e12fbfdc5eb729f',
            rev: false,
            nill: true,
            variant: 'D',
            partnumber: '88946834-01',
            airlinepn: 205,
            indent: 5,
            nomenclature: 'Stokes',
            addText: 'Fry',
            misc: 'Aliquip ad voluptate ut laboris mollit id.',
            eff: 'C',
            qty: 85,
        },
        {
            id: '5e60267fd4f15a2d439d1450',
            rev: false,
            nill: false,
            variant: 'D',
            partnumber: '82459228-81',
            airlinepn: 615,
            indent: 4,
            nomenclature: 'Cruz',
            addText: 'Glenn',
            misc: 'Ad ullamco fugiat proident ipsum nisi nostrud elit ut.',
            eff: 'A',
            qty: 100,
        },
        {
            id: '5e60267fff6d9941fb69ec30',
            rev: false,
            nill: true,
            variant: 'A',
            partnumber: '94656823-93',
            airlinepn: 232,
            indent: 4,
            nomenclature: 'Reid',
            addText: 'Perry',
            misc:
                'Do nisi pariatur aliquip eiusmod aute proident ut nisi irure pariatur.',
            eff: 'E',
            qty: 96,
        },
        {
            id: '5e60267f6d5f09e4db059ec0',
            rev: false,
            nill: false,
            variant: 'B',
            partnumber: '85848737-13',
            airlinepn: 221,
            indent: 5,
            nomenclature: 'Lori',
            addText: 'Hyde',
            misc: 'In ex Lorem nisi amet anim amet ex veniam.',
            eff: 'D',
            qty: 9,
        },
        {
            id: '5e60267f2dac84bfd39e356f',
            rev: true,
            nill: false,
            variant: 'A',
            partnumber: '89842427-16',
            airlinepn: 725,
            indent: 4,
            nomenclature: 'Ilene',
            addText: 'Kane',
            misc: 'Irure minim qui duis excepteur id amet ex irure pariatur.',
            eff: 'A',
            qty: 74,
        },
        {
            id: '5e60267f8c9ab53eae99769e',
            rev: true,
            nill: false,
            variant: 'A',
            partnumber: '97044924-70',
            airlinepn: 54,
            indent: 3,
            nomenclature: 'Rosetta',
            addText: 'Yang',
            misc:
                'Duis aliqua adipisicing qui labore irure ut aute adipisicing reprehenderit.',
            eff: 'E',
            qty: 50,
        },
        {
            id: '5e60267fa8b59a5b31bb15ac',
            rev: false,
            nill: false,
            variant: 'A',
            partnumber: '95247726-76',
            airlinepn: 417,
            indent: 4,
            nomenclature: 'Nixon',
            addText: 'Ayers',
            misc: 'Aute elit nisi id amet ad do.',
            eff: 'C',
            qty: 65,
        },
        {
            id: '5e60267fc7bd43b312d77069',
            rev: true,
            nill: true,
            variant: 'C',
            partnumber: '91449233-55',
            airlinepn: 78,
            indent: 3,
            nomenclature: 'Hayes',
            addText: 'French',
            misc:
                'Culpa sunt ipsum labore duis officia commodo reprehenderit adipisicing laboris incididunt enim ipsum aliquip.',
            eff: 'C',
            qty: 64,
        },
        {
            id: '5e60267f30417c4f2e731994',
            rev: true,
            nill: false,
            variant: 'D',
            partnumber: '95259124-08',
            airlinepn: 531,
            indent: 2,
            nomenclature: 'Bettye',
            addText: 'Blevins',
            misc: 'Eiusmod cillum Lorem reprehenderit eiusmod quis.',
            eff: 'B',
            qty: 55,
        },
        {
            id: '5e60267f8a0405b21be8eb41',
            rev: false,
            nill: true,
            variant: 'B',
            partnumber: '99346726-53',
            airlinepn: 321,
            indent: 5,
            nomenclature: 'Britt',
            addText: 'Beach',
            misc: 'Duis magna reprehenderit labore esse aute.',
            eff: 'C',
            qty: 14,
        },
        {
            id: '5e60267f0d22f71aed365567',
            rev: false,
            nill: true,
            variant: 'A',
            partnumber: '90547028-82',
            airlinepn: 102,
            indent: 4,
            nomenclature: 'Vincent',
            addText: 'Alvarado',
            misc:
                'Lorem sint voluptate in ex mollit excepteur officia elit minim.',
            eff: 'A',
            qty: 98,
        },
        {
            id: '5e60267fac63f16edf74911f',
            rev: true,
            nill: true,
            variant: 'D',
            partnumber: '87047923-25',
            airlinepn: 923,
            indent: 3,
            nomenclature: 'Holcomb',
            addText: 'Pierce',
            misc: 'Non qui fugiat duis veniam qui quis adipisicing.',
            eff: 'A',
            qty: 94,
        },
        {
            id: '5e60267f8055c32c5a5bdc35',
            rev: false,
            nill: false,
            variant: 'C',
            partnumber: '98244536-78',
            airlinepn: 106,
            indent: 4,
            nomenclature: 'Anderson',
            addText: 'Goodman',
            misc: 'Minim reprehenderit amet id esse.',
            eff: 'B',
            qty: 21,
        },
        {
            id: '5e60267fc74fbd70451796f8',
            rev: true,
            nill: true,
            variant: 'E',
            partnumber: '81940538-68',
            airlinepn: 124,
            indent: 2,
            nomenclature: 'Atkinson',
            addText: 'Sanders',
            misc: 'Duis magna dolor occaecat eu nulla.',
            eff: 'C',
            qty: 15,
        },
        {
            id: '5e60267fe66cf7011281c994',
            rev: true,
            nill: false,
            variant: 'A',
            partnumber: '86351832-76',
            airlinepn: 738,
            indent: 3,
            nomenclature: 'Cash',
            addText: 'Moore',
            misc: 'Deserunt ipsum est ex proident non velit ea eu Lorem.',
            eff: 'D',
            qty: 95,
        },
        {
            id: '5e60267f1c5f9828d8fb6d63',
            rev: false,
            nill: false,
            variant: 'B',
            partnumber: '83245524-78',
            airlinepn: 287,
            indent: 2,
            nomenclature: 'Ofelia',
            addText: 'Downs',
            misc:
                'Elit veniam esse ea enim non magna laboris sit voluptate irure exercitation velit velit.',
            eff: 'A',
            qty: 24,
        },
        {
            id: '5e60267fe0b380d067900872',
            rev: false,
            nill: true,
            variant: 'B',
            partnumber: '91453837-55',
            airlinepn: 932,
            indent: 4,
            nomenclature: 'Rosario',
            addText: 'Cain',
            misc: 'Elit deserunt voluptate sit amet amet est sit.',
            eff: 'A',
            qty: 96,
        },
        {
            id: '5e60267f19e09e0049ca6a56',
            rev: true,
            nill: true,
            variant: 'B',
            partnumber: '90053631-23',
            airlinepn: 75,
            indent: 4,
            nomenclature: 'Rosalie',
            addText: 'Dotson',
            misc:
                'Laborum laborum culpa id nostrud qui consectetur culpa et reprehenderit mollit nisi Lorem.',
            eff: 'B',
            qty: 51,
        },
        {
            id: '5e60267f50500c1e003d85ea',
            rev: true,
            nill: true,
            variant: 'A',
            partnumber: '91854138-86',
            airlinepn: 954,
            indent: 4,
            nomenclature: 'Wilma',
            addText: 'Gregory',
            misc:
                'Sunt aute nulla irure excepteur in sunt nulla dolor consectetur culpa nisi non do.',
            eff: 'D',
            qty: 96,
        },
        {
            id: '5e60267ffee74ee240811126',
            rev: true,
            nill: false,
            variant: 'C',
            partnumber: '83841531-14',
            airlinepn: 718,
            indent: 5,
            nomenclature: 'Tamika',
            addText: 'Page',
            misc:
                'Nostrud mollit est ea anim cupidatat laboris nulla laborum veniam commodo.',
            eff: 'A',
            qty: 62,
        },
        {
            id: '5e60267f919348f0cf0881e4',
            rev: false,
            nill: false,
            variant: 'C',
            partnumber: '84648931-10',
            airlinepn: 394,
            indent: 3,
            nomenclature: 'Rosie',
            addText: 'Levine',
            misc: 'Anim ea cupidatat in aute.',
            eff: 'E',
            qty: 26,
        },
        {
            id: '5e60267fe2c1512e1f0336c2',
            rev: true,
            nill: false,
            variant: 'C',
            partnumber: '99750933-53',
            airlinepn: 253,
            indent: 1,
            nomenclature: 'Gertrude',
            addText: 'Fernandez',
            misc: 'Aliquip ex deserunt incididunt velit labore non ea.',
            eff: 'B',
            qty: 47,
        },
        {
            id: '5e60267f978ff0985bc08c80',
            rev: false,
            nill: false,
            variant: 'D',
            partnumber: '92341820-95',
            airlinepn: 354,
            indent: 3,
            nomenclature: 'Harris',
            addText: 'Rowland',
            misc: 'Exercitation proident aute dolore eu deserunt velit non.',
            eff: 'E',
            qty: 72,
        },
        {
            id: '5e60267fc6a15cad9ad60ce0',
            rev: true,
            nill: true,
            variant: 'E',
            partnumber: '93840223-32',
            airlinepn: 721,
            indent: 2,
            nomenclature: 'Warner',
            addText: 'Pate',
            misc:
                'Cupidatat do ut sint veniam culpa pariatur incididunt commodo do elit non do.',
            eff: 'B',
            qty: 21,
        },
        {
            id: '5e60267f935f7e59d5a3374b',
            rev: false,
            nill: true,
            variant: 'E',
            partnumber: '93552430-43',
            airlinepn: 919,
            indent: 3,
            nomenclature: 'Deleon',
            addText: 'Bender',
            misc: 'Ex id ipsum aliqua ea nostrud consectetur irure qui.',
            eff: 'C',
            qty: 58,
        },
        {
            id: '5e60267f9df0d4460ad61d1f',
            rev: false,
            nill: true,
            variant: 'C',
            partnumber: '91247525-10',
            airlinepn: 495,
            indent: 5,
            nomenclature: 'Loraine',
            addText: 'Washington',
            misc:
                'Culpa ad consequat commodo sit in do esse labore ex tempor ut ipsum incididunt velit.',
            eff: 'D',
            qty: 56,
        },
        {
            id: '5e60267f09475dbd6f73d0f5',
            rev: false,
            nill: false,
            variant: 'D',
            partnumber: '86057123-27',
            airlinepn: 988,
            indent: 1,
            nomenclature: 'Curtis',
            addText: 'Baker',
            misc:
                'Aliquip eiusmod fugiat in deserunt officia minim mollit minim non ea aute irure.',
            eff: 'E',
            qty: 10,
        },
        {
            id: '5e60267f835abc29d2e3ba6c',
            rev: false,
            nill: false,
            variant: 'D',
            partnumber: '88555925-06',
            airlinepn: 234,
            indent: 2,
            nomenclature: 'Rios',
            addText: 'Velazquez',
            misc: 'Anim ad velit elit nisi labore.',
            eff: 'B',
            qty: 8,
        },
        {
            id: '5e60267fd35e1f0d736b79c2',
            rev: false,
            nill: true,
            variant: 'B',
            partnumber: '95743824-48',
            airlinepn: 833,
            indent: 2,
            nomenclature: 'Delores',
            addText: 'Andrews',
            misc: 'Aute consequat cillum qui magna dolore.',
            eff: 'D',
            qty: 69,
        },
        {
            id: '5e60267f238f7e66e195c7d5',
            rev: true,
            nill: true,
            variant: 'D',
            partnumber: '89853024-19',
            airlinepn: 937,
            indent: 3,
            nomenclature: 'David',
            addText: 'Russo',
            misc: 'Pariatur non do aliquip laborum elit ad ex deserunt.',
            eff: 'E',
            qty: 21,
        },
        {
            id: '5e60267f4e9662d05d3ab09c',
            rev: false,
            nill: true,
            variant: 'D',
            partnumber: '91354833-28',
            airlinepn: 784,
            indent: 2,
            nomenclature: 'Deann',
            addText: 'Cummings',
            misc:
                'Aliquip elit do proident velit anim fugiat veniam esse occaecat non sit sint.',
            eff: 'A',
            qty: 63,
        },
        {
            id: '5e60267fe1679a4c3fabf45a',
            rev: false,
            nill: false,
            variant: 'E',
            partnumber: '99048728-52',
            airlinepn: 388,
            indent: 2,
            nomenclature: 'Burris',
            addText: 'Travis',
            misc:
                'Commodo do tempor aliquip labore ipsum et aliqua aliqua ut elit.',
            eff: 'C',
            qty: 88,
        },
        {
            id: '5e60267fd66619d94e03e3d7',
            rev: true,
            nill: true,
            variant: 'B',
            partnumber: '95449828-64',
            airlinepn: 980,
            indent: 3,
            nomenclature: 'Vega',
            addText: 'Blair',
            misc: 'Amet quis esse elit nulla ex.',
            eff: 'B',
            qty: 83,
        },
        {
            id: '5e60267f5df4429315b1307b',
            rev: true,
            nill: true,
            variant: 'B',
            partnumber: '91249731-37',
            airlinepn: 13,
            indent: 1,
            nomenclature: 'Marjorie',
            addText: 'Garner',
            misc:
                'Ad labore est consequat qui deserunt deserunt id deserunt dolore occaecat eiusmod ex.',
            eff: 'B',
            qty: 48,
        },
        {
            id: '5e60267f84508c9a0b68ec1e',
            rev: false,
            nill: true,
            variant: 'D',
            partnumber: '97557837-68',
            airlinepn: 410,
            indent: 3,
            nomenclature: 'Margaret',
            addText: 'Lawson',
            misc:
                'Duis consequat proident dolor ea incididunt consequat occaecat dolore officia aute nisi aliqua proident.',
            eff: 'B',
            qty: 100,
        },
        {
            id: '5e60267f41dbf569c9c17973',
            rev: true,
            nill: true,
            variant: 'C',
            partnumber: '90145233-94',
            airlinepn: 30,
            indent: 1,
            nomenclature: 'Cooley',
            addText: 'Peterson',
            misc: 'Aliqua nulla qui fugiat sint proident.',
            eff: 'A',
            qty: 81,
        },
        {
            id: '5e60267fa849e38784f9a52b',
            rev: false,
            nill: false,
            variant: 'A',
            partnumber: '88757026-65',
            airlinepn: 164,
            indent: 4,
            nomenclature: 'Steele',
            addText: 'Workman',
            misc:
                'Anim deserunt incididunt commodo esse veniam aliquip ipsum adipisicing consequat voluptate aute pariatur nulla.',
            eff: 'D',
            qty: 87,
        },
        {
            id: '5e60267fe1d7b990e28628f5',
            rev: false,
            nill: false,
            variant: 'A',
            partnumber: '83857531-83',
            airlinepn: 25,
            indent: 2,
            nomenclature: 'Rosa',
            addText: 'Franco',
            misc:
                'Duis amet sit incididunt labore mollit laborum officia velit nostrud ullamco qui aute anim consectetur.',
            eff: 'E',
            qty: 23,
        },
        {
            id: '5e60267f375c6bc6c50f416c',
            rev: false,
            nill: false,
            variant: 'D',
            partnumber: '90658237-79',
            airlinepn: 722,
            indent: 3,
            nomenclature: 'Margarita',
            addText: 'Parker',
            misc: 'Labore do amet fugiat sint.',
            eff: 'B',
            qty: 18,
        },
        {
            id: '5e60267fafc8385e48701f10',
            rev: false,
            nill: true,
            variant: 'A',
            partnumber: '96446225-35',
            airlinepn: 558,
            indent: 4,
            nomenclature: 'Kaye',
            addText: 'Gay',
            misc: 'Mollit do ipsum dolor cillum non laboris eu.',
            eff: 'B',
            qty: 77,
        },
        {
            id: '5e60267f6b1dc814f2df4a04',
            rev: true,
            nill: true,
            variant: 'C',
            partnumber: '91552033-00',
            airlinepn: 759,
            indent: 3,
            nomenclature: 'Kitty',
            addText: 'Bryant',
            misc: 'Quis sunt anim exercitation et quis quis Lorem.',
            eff: 'E',
            qty: 74,
        },
        {
            id: '5e60267f8e8a30b9f1c121e0',
            rev: true,
            nill: true,
            variant: 'A',
            partnumber: '84047634-12',
            airlinepn: 413,
            indent: 4,
            nomenclature: 'Alicia',
            addText: 'Cleveland',
            misc: 'Mollit amet sint tempor amet cupidatat officia aliquip.',
            eff: 'E',
            qty: 60,
        },
        {
            id: '5e60267f4314ddd95dd939af',
            rev: true,
            nill: true,
            variant: 'B',
            partnumber: '94357833-73',
            airlinepn: 112,
            indent: 1,
            nomenclature: 'Arlene',
            addText: 'Blanchard',
            misc:
                'Deserunt aute Lorem incididunt voluptate irure eiusmod et in sint aliquip duis.',
            eff: 'E',
            qty: 21,
        },
        {
            id: '5e60267fb7f2496c150f4d62',
            rev: false,
            nill: false,
            variant: 'C',
            partnumber: '88858722-61',
            airlinepn: 282,
            indent: 5,
            nomenclature: 'Short',
            addText: 'Walter',
            misc:
                'Et amet voluptate quis irure mollit ipsum id eiusmod enim fugiat aliqua.',
            eff: 'B',
            qty: 29,
        },
        {
            id: '5e60267f3d7fa74e43bf8018',
            rev: false,
            nill: true,
            variant: 'C',
            partnumber: '95444724-40',
            airlinepn: 69,
            indent: 2,
            nomenclature: 'Watson',
            addText: 'Cotton',
            misc: 'Labore velit id dolor eiusmod adipisicing.',
            eff: 'B',
            qty: 11,
        },
        {
            id: '5e60267f030ccc477f67458b',
            rev: false,
            nill: true,
            variant: 'C',
            partnumber: '95857429-83',
            airlinepn: 330,
            indent: 3,
            nomenclature: 'Corina',
            addText: 'Harris',
            misc:
                'Ex dolore aliqua culpa Lorem nulla Lorem fugiat exercitation.',
            eff: 'D',
            qty: 27,
        },
        {
            id: '5e60267f97e93102f6b98063',
            rev: true,
            nill: false,
            variant: 'A',
            partnumber: '87041231-85',
            airlinepn: 317,
            indent: 1,
            nomenclature: 'Annie',
            addText: 'Owen',
            misc:
                'Fugiat est ipsum et nisi minim dolor commodo excepteur consequat sunt consequat et nisi.',
            eff: 'C',
            qty: 97,
        },
        {
            id: '5e60267f5275307c9bc3abcf',
            rev: false,
            nill: false,
            variant: 'B',
            partnumber: '94554327-43',
            airlinepn: 368,
            indent: 3,
            nomenclature: 'Tyler',
            addText: 'Leon',
            misc:
                'Sit ad id laborum eiusmod commodo nostrud nostrud dolore esse aliquip ullamco incididunt.',
            eff: 'C',
            qty: 49,
        },
        {
            id: '5e60267fc550ad2fb06d18ff',
            rev: true,
            nill: true,
            variant: 'A',
            partnumber: '87951727-59',
            airlinepn: 740,
            indent: 1,
            nomenclature: 'Mattie',
            addText: 'Sweet',
            misc: 'Ex elit ipsum esse non voluptate labore eiusmod deserunt.',
            eff: 'E',
            qty: 30,
        },
        {
            id: '5e60267f7e764ab3fc60b881',
            rev: true,
            nill: true,
            variant: 'B',
            partnumber: '94241433-74',
            airlinepn: 61,
            indent: 5,
            nomenclature: 'Margret',
            addText: 'Fuller',
            misc:
                'Commodo cillum deserunt ex dolore non veniam ut ex dolore esse.',
            eff: 'B',
            qty: 42,
        },
        {
            id: '5e60267fc2f11dc76907e657',
            rev: true,
            nill: true,
            variant: 'E',
            partnumber: '81355637-19',
            airlinepn: 924,
            indent: 5,
            nomenclature: 'Nita',
            addText: 'Butler',
            misc: 'Pariatur in fugiat ullamco esse.',
            eff: 'E',
            qty: 18,
        },
    ];
}
